import { colorPallete } from "../../environment/ColorsAndStyles";

export const orderHistoryStyles = {
  mainBody: {
    width: "100%",
    height: "152px",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative",
    background: colorPallete.orengishYellow,
  },
  internalBoxHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "95%",
    margin: "auto",
  },
  title: {
    fontFamily: "Montserrat Alternates",
    fontSize: "20px",
    fontWeight: "600",
    lineHeight: "40px",
    textAlign: "center",
    color: colorPallete.fontBlack,
  },
  date: {
    margin: "15px auto",
    color: colorPallete.fontBlack,
    fontFamily: "Montserrat Alternates",
    fontSize: "15px",
    fontWeight: "600",
    lineHeight: "20px",
    textAlign: "center",
  },
  OderContainerPaper: {
    boxShadow: "0 4px 50px rgb(0,0,0,0.1)",
    borderRadius: "10px",
    padding: "15px",
    width: { md: "45%", xs: "90%" },
  },
  orderNumber: {
    fontFamily: "Montserrat Alternates",
    fontSize: "16px",
    fontWeight: "600",
    lineHeight: "40px",
    color: colorPallete.fontBlack,
  },
  price: {
    color: colorPallete.backgroundRed,
    fontFamily: "Montserrat Alternates",
    fontSize: "14px",
    fontWeight: "600",
    lineHeight: "20px",
    textAlign: "left",
  },
  imagesAndTimeCOntainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  timeText: {
    color: "#A2A3A5",
    fontFamily: "Montserrat Alternates",
    fontSize: "14px",
    fontWeight: "600",
    lineHeight: "20px",
    textAlign: "left",
  },
};
