import { colorPallete } from "../../environment/ColorsAndStyles";

export const cartStyles = {
  headingYellowContainer: {
    height: "82px",
    background: colorPallete.orengishYellow,
    width: "100%",
    borderRadius: "10px 10px 0 0 ",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  cartText: {
    fontFamily: "Montserrat Alternates",
    fontSize: "24px",
    fontWeight: "600",
    lineHeight: "40px",
    textAlign: "center",
    color: colorPallete.fontBlack,
  },
  incrementOrDecrementBtn: {
    color: colorPallete.fontWhite,
    fontFamily: "Montserrat Alternates",
    fontSize: "32px",
    fontWeight: "500",
    lineHeight: "6px",
    textAlign: "left",
  },
  quantity: {
    fontFamily: "Montserrat Alternates",
    fontSize: "16px",
    fontWeight: "600",
    lineHeight: "6px",
  },
  submitButton: {
    color: colorPallete.fontWhite,
    fontFamily: "Montserrat Alternates",
    fontSize: "20px",
    fontWeight: 600,
    lineHeight: "24.38px",
    textAlign: "center",
    textTransform: "capitalize",
    width: "300px",
    height: "60px",
    borderRadius: "60px",
    background: colorPallete.backgroundRed,
    margin: "20px auto 50px",
    "&:hover": {
      background: colorPallete.backgroundRed,
    },
  },

  subTotal: {
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: "500",
    lineHeight: "50px",
    textAlign: "left",
    color: "#99959E",
  },
  subTotalPrice: {
    fontFamily: "Poppins",
    fontSize: "18px",
    fontWeight: "500",
    lineHeight: "50px",
    textAlign: "right",
  },
  subTotalPriceRed: {
    fontFamily: "Poppins",
    fontSize: "18px",
    fontWeight: "500",
    lineHeight: "50px",
    textAlign: "right",
    color: colorPallete.backgroundRed,
  },
  componentBody: { height: "100vh", width: "98%" },
  productsContainer: {
    marginTop: "20px",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    width: { md: "50%", xs: "100%" },
  },
  productDisplayPaper: { width: "90%", maxWidth: "400px", margin: "auto" },
  imagAndDetailsContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: { sm: "95%", xs: "98%", md: "90%" },

    padding: "10px 0px",
    margin: "auto",
  },
  productDetailsContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
  },
  productTitle: {
    fontFamily: "Montserrat Alternates",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "40px",
    textAlign: "left",
    color: colorPallete.fontBlack,
  },
  productPrice: {
    color: colorPallete.backgroundRed,
    fontFamily: "Montserrat Alternates",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "40px",
    textAlign: "left",
  },
  productPricepreDiscount: {
    opacity: "40%",
    color: colorPallete.fontBlack,
    textDecoration: "line-through",
    fontFamily: "Montserrat Alternates",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "40px",
    textAlign: "left",
  },
  incrementAndDecrementContainer: {
    borderRadius: "60px",
    width: "125px",
    background: colorPallete.orengishYellow,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    padding: "5px",
  },
  deletIcon: { color: colorPallete.backgroundRed },
  priceDetails: {
    width: { xs: "95%", sm: "90%", md: "30%" },
    margin: "auto",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
  },
  footer: {
    height: "65px",
    background: colorPallete.orengishYellow,
    width: "100%",
    borderRadius: "0 0 10px 10px  ",
    display: { xs: "flex", md: "none" },
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    position: "fixed",
    bottom: "0",
  },
};
