export const styled = {
  bgToggleCon: {
    display: { xs: "flex", sm: "none" },
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "300px",
    borderRadius: "10px 10px 0px 0px",
  },
  logoContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    bgcolor: "rgba(245, 191, 69, 1)",
    height: "127px",
    borderRadius: "10px 10px 0px 0px",
  },
  imageContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    // alignItems: "center",
    width: "80%",
  },
  listContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    // bgcolor: "aqua",
  },
  logo: {
    width: "130px",
    // border: "1px solid",
  },

  iconLogo: {
    width: "23px",
    // border: "1px solid",
  },
  activeText: {
    color: "#232323",
    fontWeight: 600,
    fontFamily: "Montserrat Alternates",
    fontSize: "17px",
  },
  navText: {
    color: "rgba(186, 185, 187, 1)",
    fontWeight: "600 !important",
    fontFamily: "Montserrat Alternates",
    fontSize: "17px",
    textWrap: "noWrap",
  },
  divider: {
    color: "rgba(0, 0, 0, 0.25)",
    width: "90%",
  },
  dividerNone: {
    display: "none",
  },
  signOutBtn: {
    mt: "5%",
    bgcolor: "rgba(245, 191, 69, 1)",
    color: "#ffffff",
    width: "270px",
    height: "55px",
    borderRadius: "45px",
    fontSize: "16px",
    fontWeight: 600,
    fontFamily: "Montserrat Alternates",
    textTransform: "capitalize",
    "&:hover": {
      bgcolor: "rgba(245, 191, 69, 1)",
      color: "#ffffff",
      width: "270px",
      height: "55px",
      borderRadius: "45px",
      fontSize: "16px",
      fontWeight: 600,
      fontFamily: "Montserrat Alternates",
      textTransform: "capitalize",
    },
  },
  version: {
    width: "85%",
    // alignSelf: "flex-start",
    mt: "55%",
    color: "rgba(186, 185, 187, 1)",
    fontWeight: "500",
    fontFamily: "Poppins",
    // mb: "5%",
    fontSize: "13px",
  },
};
