import { colorPallete } from "../../environment/ColorsAndStyles";

export const singleProductStyles = {
  componentBody: { height: "100vh" },

  swiperContainer: {
    height: "45vh",
    width: "97%",
    margin: "auto",
    position: "relative",
  },
  mainSwiperStyles: {
    height: "100%",
    maxWidth: "500px",
    "--swiper-navigation-color": colorPallete.fontWhite,
    "--swiper-pagination-bullet-inactive-color": colorPallete.fontWhite,
    "--swiper-pagination-bullet-inactive-opacity": "0.8",
    "--swiper-pagination-color": colorPallete.orengishYellow,
    "--swiper-pagination-bullet-size": "12px",
    "--swiper-pagination-bottom": "60px",
    // "--swiper-pagination-bullet-opacity": "1",
  },
  paperStyles: {
    width: { md: "95%", sm: "85%", xs: "80%" },
    margin: "auto",
    position: { xs: "absolute", md: "relative" },
    top: { xs: "calc(45vh - 50px )", md: "0" },
    left: { md: "0", sm: "7.5%", xs: "10%" },
    zIndex: 2,
    borderRadius: "20px",
  },
  wholeDetailsBox: {
    width: "95%",
    margin: "auto",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 0",
    gap: "15px",
  },
  mainDescription: {
    fontFamily: "Montserrat Alternates",
    fontSize: "18px",
    fontWeight: "600",
    lineHeight: "40px",
    textAlign: "center",
  },
  costOfProduct: {
    color: colorPallete.backgroundRed,
    fontFamily: "Montserrat Alternates",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "40px",
    textAlign: "left",
  },
  discount: {
    opacity: "40%",
    color: colorPallete.fontBlack,
    textDecoration: "line-through",
    fontFamily: "Montserrat Alternates",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "40px",
    textAlign: "left",
  },
  description: {
    fontFamily: "Poppins",
    fontSize: "15px",
    fontWeight: "500",
    lineHeight: "24px",
    textAlign: "center",
    color: colorPallete.fontGrey,
  },
  detailsNdNumericals: {
    width: { md: "50%", sm: "70%", xs: "95%" },
    margin: "auto",
  },
  incrementAndQntyContainer: {
    borderRadius: "60px",
    width: { sm: "250px", xs: "85%" },
    background: colorPallete.orengishYellow,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    padding: "1px",
    height: "30px",
  },

  incrementOrDecrementBtn: {
    color: colorPallete.fontWhite,
    fontFamily: "Montserrat Alternates",
    fontSize: "32px",
    fontWeight: "500",
    lineHeight: "6px",
    textAlign: "left",
  },
  quantity: {
    fontFamily: "Montserrat Alternates",
    fontSize: "16px",
    fontWeight: "600",
    lineHeight: "6px",
  },
  subTotal: {
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: "500",
    lineHeight: "50px",
    textAlign: "left",
    color: colorPallete.fontBlack,
  },
  subTotal2: {
    fontFamily: "Poppins",
    fontSize: "16px",
    fontWeight: "500",
    lineHeight: "50px",
    textAlign: "left",

    color: colorPallete.fontBlack,
  },
  divider: {
    color: "#fff",
    borderLeft: "1px solid #fff",
    opacity: "0.5",
  },
};
