import { colorPallete } from "../../environment/ColorsAndStyles";
import { globalStyles } from "../homeScreen/HomeStyles";

export const styles = {
  mainContainer: {
    minHeight: "100vh",
    boxSizing: "border-box",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  closeIcon: {
    bgcolor: "#e7ac27",
    "&:hover": { bgcolor: "#e7ac27" },
  },
  closeImage: {
    width: { xs: "20px", md: "25px" },
  },
  chatContainer: {
    flexGrow: 1,
    boxSizing: "border-box",
    width: "100%",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    rowGap: "20px",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    padding: "10px",
    bgcolor: "#f5f5f5",
    height: "60vh",
  },
  ownPara: {
    background: colorPallete.orengishYellow,
    textTransform: "capitalize",
    color: "white",
    padding: "5px",
    borderRadius: "10px 0px 10px 10px",
    position: "relative",
    mr: "10px",
    maxWidth: "230px",
    textAlign: "left",
    zIndex: 1,
  },
  fipolaPara: {
    bgcolor: "white",
    textTransform: "capitalize",
    color: "black",
    opacity: 0.7,
    padding: "5px",
    borderRadius: "10px 0px 10px 10px",
    position: "relative",
    mr: "10px",
    maxWidth: "230px",
    zIndex: 1,
  },
  rightArrow: {
    content: "''",
    width: "0px",
    height: "0px",
    position: "absolute",
    top: "0px",
    left: "auto",
    right: "-15px",
    bottom: "auto",
    border: "32px solid",
    borderColor: "#F5BF45 transparent transparent",
    zIndex: -1,
  },
  leftArrow: {
    width: "0px",
    height: "0px",
    position: "absolute",
    top: "0px",
    left: "-15px",
    right: "auto",
    bottom: "auto",
    border: "32px solid",
    borderColor: "#fff transparent transparent",
    zIndex: -1,
  },
  chatMainContainer: {
    width: "100%",
    boxSizing: "border-box",
  },
  fipolaImage: {
    width: "40px",
    height: "40px",
  },
  datePara: {
    ...globalStyles.boldPara,
    opacity: 0.7,
    textAlign: "center",
    width: "100%",
    mb: "15px",
  },
  inputField: {
    "& .MuiOutlinedInput-root": {
      fontFamily: "Poppins",
      fontSize: { xs: "0.8rem", sm: "1rem" },
      border: "0px none",
      boxShadow: "2px 2px 10px rgba(0,0,0,0.1)",
    },
    "& .MuiOutlinedInput-notchedOutline": {
      border: "0px none",
    },
    "& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "0px none",
    },
    "& .MuiOutlinedInput-root:hover .MuiOutlinedInput-notchedOutline": {
      border: "0px none",
    },
  },
  contentContainer: {
    overflowX: "auto",
    bgcolor: "#f5f5f5",
    mb: "10px",
  },
  content: {
    ...globalStyles.greyPara,
    bgcolor: "#fff",
    display: "inline-block",
    color: "black",
    padding: "10px",
    borderRadius: "50px",
    textWrap: "nowrap",
    fontSize: { xs: "0.9rem", md: "1rem" },
  },
};
